version: '3.1'
services:
  drupal:
#    image: drupal:10-apache
#    build:
#      context: drupal
#      dockerfile: Dockerfile
    image: drupal-base
    container_name: drupal-poc
    ports:
      - 35020:80
    environment:
      DB_USERNAME: admin
      DB_DATABASE: drupal
      DB_PASSWORD: Jijikos1
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_NAME: drupal
      DB_TABLE_PREFIX: 'dr_'
    volumes:
      # Path /drupal/shared used for file copies and tests
      - ./drupal/shared:/shared
      - ./drupal/drupal-profiles:/var/www/html/profiles
      - ./drupal/drupal-themes:/var/www/html/themes
    #  warning: the below break initial setup, recheck if going to enable them
    # - ./drupal/drupal-modules:/var/www/html/modules
    # - ./drupal/drupal-sites:/var/www/html/sites
    # - ./drupal/config:/var/www/html/sites/default
    depends_on:
      - mysql

  esap-backend:
    container_name: esap-backend
    image: esap-backend
    ports:
      - "15800:80"
      - "15801:2222"
    environment:
      REDIS_HOST: esap-webportal.redis.cache.windows.net
      REDIS_PORT: 6380
      REDIS_SSL_ENABLED: true
      REDIS_PASSWORD: wMyc3VO8SlO1QOnfajVmljjvh5LhJ56dgAzCaFrtj4I=
      SECURITY_JWT_EXPIRATION_TIME: 3600000
      SECURITY_JWT_SECRET_KEY: 6cd55a9a014b459a0de476e72bd366b318c69f1cd7bc7abae19c9b5596a6eb65
      SERVER_PORT: 80
      SPRING_APPLICATION_NAME: esap-backend
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
      SPRING_DATASOURCE_PASSWORD: Jijikos1
      SPRING_DATASOURCE_URL: jdbc:sqlserver://host.docker.internal:1433;databaseName=esap-local;encrypt=true;trustServerCertificate=true;
      SPRING_DATASOURCE_USERNAME: SA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.SQLServerDialect

  redis:
      image: redis/redis-stack:latest
      container_name: redis
      ports:
        - "6379:6379"
        - "8001:8001"
      volumes:
        - ./DB/redis/data:/data
        - ./config/redis.conf:/usr/local/etc/redis/redis.conf
#      command: redis-server --bind 0.0.0.0 --protected-mode no

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jijikos
      MYSQL_DATABASE: drupal
      MYSQL_USER: admin
      MYSQL_PASSWORD: Jijikos1
    volumes:
      - ./DB/mysql/logs:/var/log/mysql
      - ./DB/mysql/data:/var/lib/mysql
#      - ./mysql/custom-my.cnf:/etc/mysql/conf.d/custom-my.cnf
  #        - ./DB/mysql/init:/docker-entrypoint-initdb.d
  #        - ./DB/mysql/backup:/backup

  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    container_name: sqlserver
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_SA_PASSWORD=Jijikos1'
    ports:
      - '1433:1433'
    volumes:
      - ./DB/mssql/data:/var/opt/mssql/data
      - ./DB/mssql/log:/var/opt/mssql/log
      - ./DB/mssql/secrets:/var/opt/mssql/secrets

  postgres:
    image: postgres:16
    container_name: postgres_c
    ports:
      - 35022:5432
    environment:
      POSTGRES_DB: drupal_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tmp_password
    volumes:
      - ./drupal/DB/db-data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8180:8180"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - start-dev
      - --http-port=8180
      - --import-realm
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

  authserver:
    container_name: authserver
    build:
      context: AuthServer
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - keycloak
      - nexus
    restart: on-failure

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - 8095:8081
    volumes:
      - ./DB/nexus-data:/nexus-data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  db-data:
