version: '3.1'
services:
  drupal:
#    image: drupal:10-apache
    build:
      context: drupal
      dockerfile: Dockerfile
    container_name: drupal-poc
    ports:
      - 35020:80
    environment:
      DB_USERNAME: sa
      DB_DATABASE: drupal
      DB_PASSWORD: Jijikos1
      DB_HOST: host.docker.internal
      DB_PORT: 1433
      DB_NAME: drupal
      DB_TABLE_PREFIX: 'dr_'
    volumes:
      # Path /drupal/shared used for file copies and tests
      - ./drupal/shared:/shared
      - ./drupal/drupal-profiles:/var/www/html/profiles
      - ./drupal/drupal-themes:/var/www/html/themes
    #  warning: the below break initial setup, recheck if going to enable them
    # - ./drupal/drupal-modules:/var/www/html/modules
    # - ./drupal/drupal-sites:/var/www/html/sites
    # - ./drupal/config:/var/www/html/sites/default
    depends_on:
      - postgres
    networks:
      - drupal

  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    container_name: sqlserver
    environment:
      - 'ACCEPT_EULA=yes'
#      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=Jijikos1'
    ports:
      - '1433:1433'
    volumes:
      - ./DB/mssql/data:/var/opt/mssql/data
      - ./DB/mssql/log:/var/opt/mssql/log
      - ./DB/mssql/secrets:/var/opt/mssql/secrets

  postgres:
    image: postgres:16
    container_name: postgres_c
    ports:
      - 35022:5432
    environment:
      POSTGRES_DB: drupal_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tmp_password
    volumes:
      - ./drupal/DB/db-data:/var/lib/postgresql/data
    networks:
      - drupal
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8180:8180"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - start-dev
      - --http-port=8180
      - --import-realm
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - keycloak-net

  authserver:
    container_name: authserver
    build:
      context: AuthServer
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - keycloak
      - nexus
    restart: on-failure
    networks:
      - keycloak-net

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - 8095:8081
    volumes:
      - ./DB/nexus-data:/nexus-data
    networks:
      - keycloak-net

networks:
  drupal:
  keycloak-net: { }

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  db-data: